# Banknote Authentication Data Set

Данные были извлечены из изображений, полученных из подлинных и поддельных образцов банкнот. Изображения имели размер 400 на 400 пикселей и разрешение около 660 dpi. Для получения атрибутов была использована утилита Wavelet Transform.

### Атрибуты:
1. Дисперсия обработанного изображения (вещественное число)
2. Асимметрия обработанного изображения (вещественное число)
3. Эксцесс обработанного изображения (вещественное число)
4. Энтропия изображения (вещественное число)
5. Класс (целое число)

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('data_banknote_authentication.txt', sep = '\t', engine = 'python')

При попытке сделать 5 столбцов возникают проблемы:

In [22]:
data.columns = ["var","skew","cur","ent","class"]

ValueError: Length mismatch: Expected axis has 1 elements, new values have 5 elements

Приходится делать один столбец.

In [23]:
data.columns = ["var---skew---cur---ent---class"]

In [13]:
data

            var---skew---cur---ent---class
0          4.5459,8.1674,-2.4586,-1.4621,0
1           3.866,-2.6383,1.9242,0.10645,0
2          3.4566,9.5228,-4.0112,-3.5944,0
3         0.32924,-4.4552,4.5718,-0.9888,0
4          4.3684,9.6718,-3.9606,-3.1625,0
5          3.5912,3.0129,0.72888,0.56421,0
6           2.0922,-6.81,8.4636,-0.60216,0
7        3.2032,5.7588,-0.75345,-0.61251,0
8         1.5356,9.1772,-2.2718,-0.73535,0
9         1.2247,8.7779,-2.2135,-0.80647,0
10         3.9899,-2.7066,2.3946,0.86291,0
11         1.8993,7.6625,0.15394,-3.1108,0
12         -1.5768,10.843,2.5462,-2.9362,0
13         3.404,8.7261,-2.9915,-0.57242,0
14          4.6765,-3.3895,3.4896,1.4771,0
15         2.6719,3.0646,0.37158,0.58619,0
16          0.80355,2.8473,4.3439,0.6017,0
17         1.4479,-4.8794,8.3428,-2.1086,0
18         5.2423,11.0272,-4.353,-4.1013,0
19        5.7867,7.8902,-2.6196,-0.48708,0
20         0.3292,-4.4552,4.5718,-0.9888,0
21        3.9362,10.1622,-3.8235,-4.0172,0
22        0.93584,8.8855,-1.6831,-1.6599,0
23          4.4338,9.887,-4.6795,-3.7483,0
24         0.7057,-5.4981,8.3368,-2.8715,0
25        1.1432,-3.7413,5.5777,-0.63578,0
26        -0.38214,8.3909,2.1624,-3.7405,0
27         6.5633,9.8187,-4.4113,-3.2258,0
28          4.8906,-3.3584,3.4202,1.0905,0
29      -0.24811,-0.17797,4.9068,0.15429,0
...                                    ...
1341         -1.7479,-5.823,5.8699,1.212,1
1342     -0.95923,-6.7128,4.9857,0.32886,1
1343       1.3451,0.23589,-1.8785,1.3258,1
1344       2.2279,4.0951,-4.8037,-2.1112,1
1345       1.2572,4.8731,-5.2861,-5.8741,1
1346     -5.3857,9.1214,-0.41929,-5.9181,1
1347     -2.9786,2.3445,0.52667,-0.40173,1
1348       -1.5851,-2.1562,1.7082,0.9017,1
1349    -0.21888,-2.2038,-0.0954,0.56421,1
1350      1.3183,1.9017,-3.3111,0.065071,1
1351       1.4896,3.4288,-4.0309,-1.4259,1
1352      0.11592,3.2219,-3.4302,-2.8457,1
1353     -3.3924,3.3564,-0.72004,-3.5233,1
1354     -6.1632,8.7096,-0.21621,-3.6345,1
1355     -4.0786,2.9239,0.87026,-0.65389,1
1356     -2.5899,-0.3911,0.93452,0.42972,1
1357  -1.0116,-0.19038,-0.90597,0.003003,1
1358    0.066129,2.4914,-2.9401,-0.62156,1
1359    -0.24745,1.9368,-2.4697,-0.80518,1
1360     -1.5732,1.0636,-0.71232,-0.8388,1
1361      -2.1668,1.5933,0.045122,-1.678,1
1362      -1.1667,-1.4237,2.9241,0.66119,1
1363      -2.8391,-6.63,10.4849,-0.42113,1
1364    -4.5046,-5.8126,10.8867,-0.52846,1
1365       -2.41,3.7433,-0.40215,-1.2953,1
1366     0.40614,1.3492,-1.4501,-0.55949,1
1367      -1.3887,-4.8773,6.4774,0.34179,1
1368    -3.7503,-13.4586,17.5932,-2.7771,1
1369      -3.5637,-8.3827,12.393,-1.2823,1
1370      -2.5419,-0.65804,2.6842,1.1952,1

[1371 rows x 1 columns]

In [14]:
print(data)

            var---skew---cur---ent---class
0          4.5459,8.1674,-2.4586,-1.4621,0
1           3.866,-2.6383,1.9242,0.10645,0
2          3.4566,9.5228,-4.0112,-3.5944,0
3         0.32924,-4.4552,4.5718,-0.9888,0
4          4.3684,9.6718,-3.9606,-3.1625,0
5          3.5912,3.0129,0.72888,0.56421,0
6           2.0922,-6.81,8.4636,-0.60216,0
7        3.2032,5.7588,-0.75345,-0.61251,0
8         1.5356,9.1772,-2.2718,-0.73535,0
9         1.2247,8.7779,-2.2135,-0.80647,0
10         3.9899,-2.7066,2.3946,0.86291,0
11         1.8993,7.6625,0.15394,-3.1108,0
12         -1.5768,10.843,2.5462,-2.9362,0
13         3.404,8.7261,-2.9915,-0.57242,0
14          4.6765,-3.3895,3.4896,1.4771,0
15         2.6719,3.0646,0.37158,0.58619,0
16          0.80355,2.8473,4.3439,0.6017,0
17         1.4479,-4.8794,8.3428,-2.1086,0
18         5.2423,11.0272,-4.353,-4.1013,0
19        5.7867,7.8902,-2.6196,-0.48708,0
20         0.3292,-4.4552,4.5718,-0.9888,0
21        3.9362,10.1622,-3.8235,-4.0172,0
22        0.93584,8.8855,-1.6831,-1.6599,0
23          4.4338,9.887,-4.6795,-3.7483,0
24         0.7057,-5.4981,8.3368,-2.8715,0
25        1.1432,-3.7413,5.5777,-0.63578,0
26        -0.38214,8.3909,2.1624,-3.7405,0
27         6.5633,9.8187,-4.4113,-3.2258,0
28          4.8906,-3.3584,3.4202,1.0905,0
29      -0.24811,-0.17797,4.9068,0.15429,0
...                                    ...
1341         -1.7479,-5.823,5.8699,1.212,1
1342     -0.95923,-6.7128,4.9857,0.32886,1
1343       1.3451,0.23589,-1.8785,1.3258,1
1344       2.2279,4.0951,-4.8037,-2.1112,1
1345       1.2572,4.8731,-5.2861,-5.8741,1
1346     -5.3857,9.1214,-0.41929,-5.9181,1
1347     -2.9786,2.3445,0.52667,-0.40173,1
1348       -1.5851,-2.1562,1.7082,0.9017,1
1349    -0.21888,-2.2038,-0.0954,0.56421,1
1350      1.3183,1.9017,-3.3111,0.065071,1
1351       1.4896,3.4288,-4.0309,-1.4259,1
1352      0.11592,3.2219,-3.4302,-2.8457,1
1353     -3.3924,3.3564,-0.72004,-3.5233,1
1354     -6.1632,8.7096,-0.21621,-3.6345,1
1355     -4.0786,2.9239,0.87026,-0.65389,1
1356     -2.5899,-0.3911,0.93452,0.42972,1
1357  -1.0116,-0.19038,-0.90597,0.003003,1
1358    0.066129,2.4914,-2.9401,-0.62156,1
1359    -0.24745,1.9368,-2.4697,-0.80518,1
1360     -1.5732,1.0636,-0.71232,-0.8388,1
1361      -2.1668,1.5933,0.045122,-1.678,1
1362      -1.1667,-1.4237,2.9241,0.66119,1
1363      -2.8391,-6.63,10.4849,-0.42113,1
1364    -4.5046,-5.8126,10.8867,-0.52846,1
1365       -2.41,3.7433,-0.40215,-1.2953,1
1366     0.40614,1.3492,-1.4501,-0.55949,1
1367      -1.3887,-4.8773,6.4774,0.34179,1
1368    -3.7503,-13.4586,17.5932,-2.7771,1
1369      -3.5637,-8.3827,12.393,-1.2823,1
1370      -2.5419,-0.65804,2.6842,1.1952,1

[1371 rows x 1 columns]

In [15]:
data.head()

     var---skew---cur---ent---class
0   4.5459,8.1674,-2.4586,-1.4621,0
1    3.866,-2.6383,1.9242,0.10645,0
2   3.4566,9.5228,-4.0112,-3.5944,0
3  0.32924,-4.4552,4.5718,-0.9888,0
4   4.3684,9.6718,-3.9606,-3.1625,0

In [16]:
data.tail()

          var---skew---cur---ent---class
1366   0.40614,1.3492,-1.4501,-0.55949,1
1367    -1.3887,-4.8773,6.4774,0.34179,1
1368  -3.7503,-13.4586,17.5932,-2.7771,1
1369    -3.5637,-8.3827,12.393,-1.2823,1
1370    -2.5419,-0.65804,2.6842,1.1952,1

В таблице 1371 строка и 1 столбец.

In [17]:
print(data.shape)

(1371, 1)

Применять эту и другие подобные команды не имеет смысла.

In [18]:
print(data.columns)

Index([u'var---skew---cur---ent---class'], dtype='object')